name: 'Tests: ESLint (8)'

on: [pull_request, push]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
      minors: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          versionsAsRoot: true
          type: majors
          preset: '^20.19.0 || ^22.13.0 || >=24'

  latest:
    needs: [matrix]
    name: 'latest majors'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.latest) }}
        eslint:
          - 8
          - 8.57.0
        babel-eslint:
          - 10
          - 9
          - 8
        typescript-eslint:
          - 5
          - 6
          - 7
          - 8

    steps:
      - uses: actions/checkout@v4
      - name: strip eslint-doc-generator to avoid peer conflicts
        if: ${{ matrix.typescript-eslint >= 6 }}
        run: echo "$(jq 'del(.devDependencies["eslint-doc-generator"])' package.json)" > package.json
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          after_install: |
            npm install --no-save "eslint@${{ matrix.eslint }}" "@typescript-eslint/parser@${{ matrix.typescript-eslint == 8 && 8.17 || matrix.typescript-eslint }}" "babel-eslint@${{ matrix.babel-eslint }}"
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: "${{ matrix.typescript-eslint >= 6 && 'false' || 'true' }}"
      - run: npx ls-engines
      - run: npm run unit-test
      - uses: codecov/codecov-action@v3.1.5

  node:
    name: 'eslint 8'
    needs: [latest]
    runs-on: ubuntu-latest
    steps:
      - run: true
